install: true
language: cpp
compiler: g++
script:
- git clone https://github.com/google/googletest.git
- cd googletest
- cmake .
- make clean
- make all
- cd ..
- make GOOGLETEST=/googletest
- make all
- make test
