install: true
language: cpp
compiler: g++
script:
- git clone https://github.com/google/googletest.git
- pwd
- ls
- cd googletest
- ls
- cmake .
- make clean
- make all
- cd ..
- pwd
- ls
- make GOOGLETEST=./googletest
- make all
- make test
